// scripts.js — auto-populated from videos.json (generated by GitHub Actions)
document.addEventListener("DOMContentLoaded", function () {

  function buildGrid(containerId, videos) {
    const grid = document.getElementById(containerId);
    if (!grid) return;

    videos.forEach(video => {
      const card = document.createElement("div");
      card.className = "video";

      // thumbnail (wrapped in link to open YouTube on click)
      const link = document.createElement("a");
      link.href = `https://youtu.be/${video.id}`;
      link.target = "_blank";
      link.rel = "noopener noreferrer";

      const thumb = document.createElement("img");
      thumb.className = "thumb";
      thumb.src = `https://img.youtube.com/vi/${video.id}/hqdefault.jpg`;
      thumb.alt = video.title || "Video thumbnail";
      link.appendChild(thumb);
      card.appendChild(link);

      // iframe — src intentionally blank until hover
      const player = document.createElement("iframe");
      player.className = "player";
      player.allow = "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share";
      player.referrerPolicy = "strict-origin-when-cross-origin";
      player.allowFullscreen = true;
      card.appendChild(player);

      // hover: load & autoplay on enter, stop instantly on leave
      card.addEventListener("mouseenter", () => {
        player.src = `https://www.youtube.com/embed/${video.id}?autoplay=1&mute=1`;
      });
      card.addEventListener("mouseleave", () => {
        player.src = "";
      });

      // title + view count
      const info = document.createElement("div");
      info.className = "video-info";

      const title = document.createElement("p");
      title.className = "video-title";
      title.textContent = video.title || "";
      info.appendChild(title);

      if (video.views) {
        const views = document.createElement("p");
        views.className = "video-views";
        views.textContent = formatViews(video.views) + " views";
        info.appendChild(views);
      }

      card.appendChild(info);
      grid.appendChild(card);
    });
  }

  function formatViews(n) {
    n = parseInt(n, 10);
    if (n >= 1000000) return (n / 1000000).toFixed(1) + "M";
    if (n >= 1000) return (n / 1000).toFixed(1) + "K";
    return n.toString();
  }

  fetch("videos.json?t=" + Date.now())
    .then(r => r.json())
    .then(data => {
      const videos = data.videos || [];
      buildGrid("allVideosGrid", videos);

      const meta = document.getElementById("archiveMeta");
      if (meta && videos.length > 0) {
        meta.textContent = videos.length + " live shows — sorted by popularity";
      }

      const subtitle = document.getElementById("subtitle");
      if (subtitle && data.updated) {
        const d = new Date(data.updated);
        subtitle.textContent = "Updated " + d.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
      }
    })
    .catch(err => {
      console.error("Could not load videos.json:", err);
      const grid = document.getElementById("allVideosGrid");
      if (grid) grid.innerHTML = '<p style="color:#888;padding:40px">Video archive loading...</p>';
    });

  // scroll-to-top
  const scrollBtn = document.getElementById("scrollTopBtn");
  if (scrollBtn) {
    window.addEventListener("scroll", () => {
      scrollBtn.style.opacity = window.scrollY > 300 ? 1 : 0;
      scrollBtn.style.visibility = window.scrollY > 300 ? "visible" : "hidden";
    });
    scrollBtn.addEventListener("click", () => window.scrollTo({ top: 0, behavior: "smooth" }));
  }
});
