// scripts.js — auto-populated from videos.json (generated by GitHub Actions)
document.addEventListener("DOMContentLoaded", function () {

  // === LIGHTBOX ===
  const overlay = document.createElement("div");
  overlay.id = "lightbox";
  overlay.innerHTML = `<div id="lightbox-inner"><button id="lightbox-close">✕</button><iframe id="lightbox-iframe" allowfullscreen allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin"></iframe></div>`;
  document.body.appendChild(overlay);

  const iframe = document.getElementById("lightbox-iframe");

  function openLightbox(videoId) {
    iframe.src = `https://www.youtube.com/embed/${videoId}?autoplay=1`;
    overlay.classList.add("active");
    document.body.style.overflow = "hidden";
  }
  function closeLightbox() {
    overlay.classList.remove("active");
    iframe.src = "";
    document.body.style.overflow = "";
  }

  document.getElementById("lightbox-close").addEventListener("click", closeLightbox);
  overlay.addEventListener("click", (e) => { if (e.target === overlay) closeLightbox(); });
  document.addEventListener("keydown", (e) => { if (e.key === "Escape") closeLightbox(); });

  // === GRID ===
  function buildGrid(containerId, videos) {
    const grid = document.getElementById(containerId);
    if (!grid) return;
    videos.forEach(video => {
      const card = document.createElement("div");
      card.className = "video";
      const thumb = document.createElement("img");
      thumb.className = "thumb";
      thumb.src = `https://img.youtube.com/vi/${video.id}/hqdefault.jpg`;
      thumb.alt = video.title || "Video thumbnail";
      const playIcon = document.createElement("div");
      playIcon.className = "play-icon";
      playIcon.innerHTML = "▶";
      card.appendChild(thumb);
      card.appendChild(playIcon);
      card.addEventListener("click", () => openLightbox(video.id));
      const info = document.createElement("div");
      info.className = "video-info";
      const title = document.createElement("p");
      title.className = "video-title";
      title.textContent = video.title || "";
      info.appendChild(title);
      if (video.views) {
        const views = document.createElement("p");
        views.className = "video-views";
        views.textContent = formatViews(video.views) + " views";
        info.appendChild(views);
      }
      card.appendChild(info);
      grid.appendChild(card);
    });
  }

  function formatViews(n) {
    n = parseInt(n, 10);
    if (n >= 1000000) return (n / 1000000).toFixed(1) + "M";
    if (n >= 1000) return (n / 1000).toFixed(1) + "K";
    return n.toString();
  }

  fetch("videos.json?t=" + Date.now())
    .then(r => r.json())
    .then(data => {
      const videos = data.videos || [];
      buildGrid("allVideosGrid", videos);
      const meta = document.getElementById("archiveMeta");
      if (meta && videos.length > 0) meta.textContent = videos.length + " live shows — sorted by popularity";
      const subtitle = document.getElementById("subtitle");
      if (subtitle && data.updated) {
        const d = new Date(data.updated);
        subtitle.textContent = "Updated " + d.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
      }
    })
    .catch(() => {
      const grid = document.getElementById("allVideosGrid");
      if (grid) grid.innerHTML = `<p style="color:#888;padding:40px">Video archive loading...</p>`;
    });

  const scrollBtn = document.getElementById("scrollTopBtn");
  if (scrollBtn) {
    window.addEventListener("scroll", () => {
      scrollBtn.style.opacity = window.scrollY > 300 ? 1 : 0;
      scrollBtn.style.visibility = window.scrollY > 300 ? "visible" : "hidden";
    });
    scrollBtn.addEventListener("click", () => window.scrollTo({ top: 0, behavior: "smooth" }));
  }
});
